countries_data = [
    # Afrika
    {"continent": "Afrika", "country_de": "Marokko",    "country_en": "Morocco"},
    {"continent": "Afrika", "country_de": "Algerien",   "country_en": "Algeria"},
    {"continent": "Afrika", "country_de": "Tunesien",   "country_en": "Tunisia"},
    {"continent": "Afrika", "country_de": "Libyen",     "country_en": "Libya"},
    {"continent": "Afrika", "country_de": "Ägypten",    "country_en": "Egypt"},
    {"continent": "Afrika", "country_de": "Äthiopien",  "country_en": "Ethiopia"},
    {"continent": "Afrika", "country_de": "Eritrea",    "country_en": "Eritrea"},
    {"continent": "Afrika", "country_de": "Kenia",      "country_en": "Kenya"},
    {"continent": "Afrika", "country_de": "Somalia",    "country_en": "Somalia"},
    {"continent": "Afrika", "country_de": "Mali",       "country_en": "Mali"},
    {"continent": "Afrika", "country_de": "Ghana",      "country_en": "Ghana"},
    {"continent": "Afrika", "country_de": "Demokratische Republik Kongo", "country_en": "Democratic Republic of the Congo"},
    {"continent": "Afrika", "country_de": "Nigeria",    "country_en": "Nigeria"},
    {"continent": "Afrika", "country_de": "Madagaskar", "country_en": "Madagascar"},
    {"continent": "Afrika", "country_de": "Südafrika",  "country_en": "South Africa"},

    # Asien
    {"continent": "Asien", "country_de": "China",         "country_en": "China"},
    {"continent": "Asien", "country_de": "Indien",        "country_en": "India"},
    {"continent": "Asien", "country_de": "Indonesien",    "country_en": "Indonesia"},
    {"continent": "Asien", "country_de": "Thailand",      "country_en": "Thailand"},
    {"continent": "Asien", "country_de": "Bangladesch",   "country_en": "Bangladesh"},
    {"continent": "Asien", "country_de": "Japan",         "country_en": "Japan"},
    {"continent": "Asien", "country_de": "Pakistan",      "country_en": "Pakistan"},
    {"continent": "Asien", "country_de": "Afghanistan",   "country_en": "Afghanistan"},
    {"continent": "Asien", "country_de": "Saudi-Arabien", "country_en": "Saudi Arabia"},
    {"continent": "Asien", "country_de": "Südkorea",      "country_en": "South Korea"},
    {"continent": "Asien", "country_de": "Nordkorea",     "country_en": "North Korea"},
    {"continent": "Asien", "country_de": "Syrien",        "country_en": "Syria"},
    {"continent": "Asien", "country_de": "Iran",          "country_en": "Iran"},
    {"continent": "Asien", "country_de": "Irak",          "country_en": "Iraq"},
    {"continent": "Asien", "country_de": "Malaysia",      "country_en": "Malaysia"},
    {"continent": "Asien", "country_de": "Philippinen",   "country_en": "Philippines"},

    # Europa (inkl. Türkei und Russland)
    {"continent": "Europa", "country_de": "Albanien",              "country_en": "Albania"},
    {"continent": "Europa", "country_de": "Andorra",               "country_en": "Andorra"},
    {"continent": "Europa", "country_de": "Belarus",               "country_en": "Belarus"},
    {"continent": "Europa", "country_de": "Belgien",               "country_en": "Belgium"},
    {"continent": "Europa", "country_de": "Bosnien-Herzegowina",   "country_en": "Bosnia and Herzegovina"},
    {"continent": "Europa", "country_de": "Bulgarien",             "country_en": "Bulgaria"},
    {"continent": "Europa", "country_de": "Dänemark",              "country_en": "Denmark"},
    {"continent": "Europa", "country_de": "Deutschland",           "country_en": "Germany"},
    {"continent": "Europa", "country_de": "Estland",               "country_en": "Estonia"},
    {"continent": "Europa", "country_de": "Finnland",              "country_en": "Finland"},
    {"continent": "Europa", "country_de": "Frankreich",            "country_en": "France"},
    {"continent": "Europa", "country_de": "Griechenland",          "country_en": "Greece"},
    {"continent": "Europa", "country_de": "Großbritannien",        "country_en": "United Kingdom"},
    {"continent": "Europa", "country_de": "Irland",                "country_en": "Ireland"},
    {"continent": "Europa", "country_de": "Island",                "country_en": "Iceland"},
    {"continent": "Europa", "country_de": "Italien",               "country_en": "Italy"},
    {"continent": "Europa", "country_de": "Kosovo",                "country_en": "Kosovo"},
    {"continent": "Europa", "country_de": "Kroatien",              "country_en": "Croatia"},
    {"continent": "Europa", "country_de": "Lettland",              "country_en": "Latvia"},
    {"continent": "Europa", "country_de": "Liechtenstein",         "country_en": "Liechtenstein"},
    {"continent": "Europa", "country_de": "Litauen",               "country_en": "Lithuania"},
    {"continent": "Europa", "country_de": "Luxemburg",             "country_en": "Luxembourg"},
    {"continent": "Europa", "country_de": "Malta",                 "country_en": "Malta"},
    {"continent": "Europa", "country_de": "Moldowa",               "country_en": "Moldova"},
    {"continent": "Europa", "country_de": "Monaco",                "country_en": "Monaco"},
    {"continent": "Europa", "country_de": "Montenegro",            "country_en": "Montenegro"},
    {"continent": "Europa", "country_de": "Niederlande",           "country_en": "Netherlands"},
    {"continent": "Europa", "country_de": "Nordmazedonien",        "country_en": "North Macedonia"},
    {"continent": "Europa", "country_de": "Norwegen",              "country_en": "Norway"},
    {"continent": "Europa", "country_de": "Österreich",            "country_en": "Austria"},
    {"continent": "Europa", "country_de": "Polen",                 "country_en": "Poland"},
    {"continent": "Europa", "country_de": "Portugal",              "country_en": "Portugal"},
    {"continent": "Europa", "country_de": "Rumänien",              "country_en": "Romania"},
    {"continent": "Europa", "country_de": "Russland",              "country_en": "Russia"},
    {"continent": "Europa", "country_de": "San Marino",            "country_en": "San Marino"},
    {"continent": "Europa", "country_de": "Schweiz",               "country_en": "Switzerland"},
    {"continent": "Europa", "country_de": "Schweden",              "country_en": "Sweden"},
    {"continent": "Europa", "country_de": "Serbien",               "country_en": "Serbia"},
    {"continent": "Europa", "country_de": "Slowakei",              "country_en": "Slovakia"},
    {"continent": "Europa", "country_de": "Slowenien",             "country_en": "Slovenia"},
    {"continent": "Europa", "country_de": "Spanien",               "country_en": "Spain"},
    {"continent": "Europa", "country_de": "Tschechien",            "country_en": "Czech Republic"},
    {"continent": "Europa", "country_de": "Türkei",                "country_en": "Turkey"},
    {"continent": "Europa", "country_de": "Ukraine",               "country_en": "Ukraine"},
    {"continent": "Europa", "country_de": "Ungarn",                "country_en": "Hungary"},
    {"continent": "Europa", "country_de": "Vatikanstadt",          "country_en": "Vatican City"},

    # Nordamerika
    {"continent": "Nordamerika", "country_de": "Jamaika", "country_en": "Jamaica"},
    {"continent": "Nordamerika", "country_de": "Kanada",  "country_en": "Canada"},
    {"continent": "Nordamerika", "country_de": "Kuba",    "country_en": "Cuba"},
    {"continent": "Nordamerika", "country_de": "Mexiko",  "country_en": "Mexico"},
    {"continent": "Nordamerika", "country_de": "USA",     "country_en": "United States"},

    # Südamerika
    {"continent": "Südamerika", "country_de": "Argentinien", "country_en": "Argentina"},
    {"continent": "Südamerika", "country_de": "Bolivien",    "country_en": "Bolivia"},
    {"continent": "Südamerika", "country_de": "Brasilien",   "country_en": "Brazil"},
    {"continent": "Südamerika", "country_de": "Chile",       "country_en": "Chile"},
    {"continent": "Südamerika", "country_de": "Peru",        "country_en": "Peru"},
    {"continent": "Südamerika", "country_de": "Venezuela",   "country_en": "Venezuela"},
    {"continent": "Südamerika", "country_de": "Kolumbien",   "country_en": "Colombia"},
    {"continent": "Südamerika", "country_de": "Ecuador",     "country_en": "Ecuador"},

    # Australien/Ozeanien
    {"continent": "Austrálie/Oceánie", "country_de": "Australien", "country_en": "Australia"},
    {"continent": "Austrálie/Oceánie", "country_de": "Neuseeland", "country_en": "New Zealand"},
]

